---
title: "Posterior Predictive Distribution"
output:
  pdf_document: default
  html_document: default
---

Having derived the posterior distribution for a parameter $\theta$ given a sample $y = (y_1, y_2, \ldots, y_n)$, the posterior predictive distribution for a new observation $y_{n+1}$ is defined as

$$
f(y_{n+1}\mid y) = \int_{-\infty}^{\infty} f(\theta\mid y) f(y_{n+1} \mid \theta) d\theta
$$

where $f(\theta \mid y)$ is the posterior distribution and $f(y_{n+1} \mid \theta)$ is the likelihood contribution of the new observation.

Derive the posterior predictive distribution for a new observation for the case of an i.i.d. sample $y$ of a normal distribution $N(\mu, \sigma^2)$ with known variance $\sigma^2$ and flat constant prior 1 for $\mu$.

Reformulating the integral,

$$
f_y(y_{n+1}\mid y) = \int_{-\infty}^{\infty} f_\mu(\gamma\mid y, \sigma^2) f_y(y_{n+1} \mid \gamma, \sigma^2) d\gamma
$$

We know that normal distributions are conjugate priors with each other. First, we prove that, given $\bar y = \Sigma_i y_i/n$

$$
\sum_i (y_i - \gamma)^2 = \sum_i (y_i - \bar y)^2 + n(\bar y - \gamma)^2
$$

Indeed,

$$
\begin{align}
\sum_i (y_i - \gamma)^2 &= \sum_i (y_i - \bar y + \bar y - \gamma)^2 \\
&= \sum_i [(y_i - \bar y)^2 + 2(y_i - \bar y)(\bar y - \gamma) + (\bar y - \gamma)^2] \\
&= \sum_i (y_i - \bar y)^2 + 2\left(\Sigma_i y_i - n\bar y\right)(\bar y - \gamma ) + n(\bar y - \gamma)^2 \\
&= \sum_i (y_i - \bar y)^2 + n(\bar y - \gamma)^2
\end{align}
$$

hence

$$
\begin{align}
f_\mu (\mu \mid y, \sigma^2) &\propto f_y(y \mid \mu, \sigma^2) f_\mu(\mu) \\
&\propto \exp\left(-\frac{\sum_i (y_i - \mu)^2}{2\sigma^2}\right) \\
&\propto \exp\left(-\frac{(\bar y - \gamma)^2}{2 \sigma^2/n}\right)
\end{align}
$$

which results in $\mu \mid y \sim N(\bar y, \sigma^2/n)$. We substitute the expression to the posterior predictive distribution for a new observation $y_{n+1}$:

$$
\begin{align}
f_y(y_{n+1}\mid y) &= \int_{-\infty}^{\infty} f_\mu(\gamma\mid y, \sigma^2) f_y(y_{n+1} \mid \gamma, \sigma^2) d\gamma \\
&= \int_{-\infty}^{\infty} \sqrt{\frac{n}{2\pi\sigma^2}} \exp\left(-\frac{(\bar y - \gamma)^2}{2\sigma^2/n}\right) \sqrt{\frac{1}{2\pi\sigma^2}} \exp \left(- \frac{(\gamma - y_{n+1})^2}{2\sigma^2}\right) d\gamma \\
&= \frac{\sqrt n}{2\pi\sigma^2} \int_{-\infty}^{\infty} \exp\left(-\frac{n(\bar y - \gamma)^2 + (\gamma - y_{n+1})^2}{2\sigma^2}\right)   d\gamma
\end{align}
$$

Let's work on the inside of the exponent.

$$
\begin{align}
n(\gamma - \bar y)^2 + (\gamma - y_{n+1})^2  &= n(\gamma^2 - 2\gamma \bar y + \bar y ^2) + (\gamma^2 - 2\gamma y_{n+1} + y_{n+1}^2)\\ 
&= (n+1)\gamma^2 -2(n\bar y + y_{n+1})\gamma + n\bar y ^2 + y_{n+1}^2
\end{align}
$$

We can complete the square to isolate the $\gamma$:

$$\begin{align}
(n+1)\gamma^2 -2(n\bar y + y_{n+1})\gamma + n\bar y ^2 + y_n^2 &= (n+1)\left(\gamma - \frac{n\bar y + y_{n+1}}{n+1}\right)^2 + n\bar y ^2 + y_{n+1} ^2 - \frac{(n\bar y + y_{n+1})^2}{n+1} \\
&= (n+1)\left(\gamma - \frac{n\bar y + y_{n+1}}{n+1}\right)^2 \\
&+ \frac{n^2\bar y^2 + n y_{n+1}^2 + n\bar y ^2 + y_{n+1} ^2 - n^2\bar y ^2 - 2n\bar y y_{n+1} - y_{n+1}^2}{n+1} \\
&= (n+1)\left(\gamma - \frac{n\bar y + y_{n+1}}{n+1}\right)^2 + \frac{n y_{n+1}^2 + n\bar y ^2 - 2n\bar y y_{n+1}}{n+1} \\
&= (n+1)\left(\gamma - \frac{n\bar y + y_{n+1}}{n+1}\right)^2 + \frac{n}{n+1}(y_{n+1} - \bar y)^2
\end{align}
$$

We substitute that into $f_y(y_{n+1}\mid y)$, letting $m =\frac{n\bar y + y_{n+1}}{n+1}$

$$ \begin{align}
&\frac{\sqrt n}{2\pi\sigma^2} \int_{-\infty}^{\infty} \exp\left(-\frac{n(\bar y - \gamma)^2 + (\gamma - y_{n+1})^2}{2\sigma^2}\right)   d\gamma \\
&= \frac{\sqrt n e^{-\frac{n(y_{n+1} - \bar y)^2}{2\sigma^2(n+1)}}}{2\pi\sigma^2} \int_{-\infty}^{\infty} e^{-\frac{(\gamma - m)^2}{2\sigma^2/(n+1)}}d\gamma \\
&=\frac{\sqrt n e^{-\frac{n(y_{n+1} - \bar y)^2}{2\sigma^2(n+1)}}}{2\pi\sigma^2} \sqrt{\frac{2\pi \sigma^2}{n+1}} \\
&= \sqrt{\frac{n}{n+1}} \frac{1}{\sqrt{2\pi\sigma^2}} \exp\left\{-\frac{n}{n+1}\cdot\frac{(y_{n+1} - \bar y)^2}{2\sigma^2}\right\}
\end{align}
$$

Hence we have

$$
f_{y}(y_{n+1} \mid y) = \sqrt{\frac{n}{n+1}} \frac{1}{\sqrt{2\pi\sigma^2}} \exp\left\{-\frac{n}{n+1}\cdot\frac{(y_{n+1} - \bar y)^2}{2\sigma^2}\right\} 
$$

as our posterior prediction distribution for the new observation $y_{n+1}$. In fact, this is the distribution $N\left(\bar y, \frac{\sigma^2(n+1)}{n}\right)$.
